server:
  port: 9002
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root1234@localhost:9000/eureka
      
uploadPath: d:/uploadFile/
      
spring:
  application:
    name: xgzx-admin
  datasource:
    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/xgzx?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  mvc:
    #所有访问都经过静态文件路径
    static-path-pattern: /static/**
  resources:
    static-locations: file:${uploadPath},/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 100Mb  
      
      
mybatis-plus: 
  mapper-locations: classpath:com/xgzx/admin/mapper/xml/*Mapper.xml
  typeAliasesPackage: com.xgzx.admin.entity
  configuration:
    #解决，查询返回结果含null没有对应字段值问题  
    callSettersOnNulls: true
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #刷新mapper 调试神器
    refresh-mapper: false
    #日期自动填充
    meta-object-handler: com.xgzx.admin.config.DbTimeHandler
    
wx:
  certPath: D://Program Files/weixin/cert/apiclient_cert.p12
  #certPath: /home/certs/apiclient_cert.p12
  #每小时执行
  quartztimer: 0 0 0/1 * * ?
  #每60秒执行
#  quartztimer: 0/60 * * * * ?
  mchName: DONG网络工作室
  
